name: Test
on: [push, pull_request]

jobs:
  build:
    name: Build & Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.20.x'
    - name: Validate JSON
      run: |
        cat products.json | jq '.' >> /dev/null
    - name: go build
      run:  make build
    - name: go vet
      run: go vet ./...
